#!/bin/bash

cd ~/Code/dpd-db

# Ensure the logs directory exists
mkdir -p logs

# Generate a timestamp
timestamp=$(date +"%Y-%m-%d_%H-%M-%S")

# Run the command and save output with timestamped filename
script -q -c "bash scripts/bash/initial_build_db.sh" | tee >(ansi2html > "logs/build_$timestamp.html")
