from tools.cst_source.parsers.abhidhamma import (
    Abh1Parser,
    Abh2Parser,
    Abh3Parser,
    Abh4Parser,
    Abh5Parser,
    Abh6Parser,
    Abh7Parser,
)
from tools.cst_source.parsers.base import BookParser
from tools.cst_source.parsers.commentary import (
    AbhaParser,
    AnaParser,
    AntParser,
    DnaParser,
    DntParser,
    Kn1aParser,
    Kn2aParser,
    Kn3aParser,
    Kn4aParser,
    Kn5aParser,
    Kn6aParser,
    Kn7aParser,
    Kn8aKn9aParser,
    Kn10aParser,
    Kn12aParser,
    Kn13aParser,
    Kn14aParser,
    Kn15aParser,
    Kn16aParser,
    Kn17aParser,
    Kn19aParser,
    MnaParser,
    MntParser,
    SnaParser,
    SntParser,
    VinaParser,
)
from tools.cst_source.parsers.khuddaka import (
    Kn1Parser,
    Kn2Parser,
    Kn3Parser,
    Kn4Parser,
    Kn5Parser,
    Kn6Parser,
    Kn7Parser,
    Kn8Kn9Parser,
    Kn10Kn11Parser,
    Kn12Parser,
    Kn13Parser,
    Kn14Parser,
    Kn15Parser,
    Kn16Parser,
    Kn17Parser,
    Kn18Parser,
    Kn19Parser,
    Kn20Parser,
)
from tools.cst_source.parsers.misc import (
    ApParser,
    AptParser,
    KvaParser,
    VismParser,
)
from tools.cst_source.parsers.sutta import (
    AnguttaraParser,
    DighaParser,
    MajjhimaParser,
    SamyuttaParser,
)
from tools.cst_source.parsers.vinaya import (
    Vin1Parser,
    Vin2Parser,
    Vin3Vin4Parser,
    Vin5Parser,
)

PARSER_CLASSES: list[type[BookParser]] = [
    # vinaya
    Vin1Parser,
    Vin2Parser,
    Vin3Vin4Parser,
    Vin5Parser,
    # sutta
    DighaParser,
    MajjhimaParser,
    SamyuttaParser,
    AnguttaraParser,
    # khuddaka
    Kn1Parser,
    Kn2Parser,
    Kn3Parser,
    Kn4Parser,
    Kn5Parser,
    Kn6Parser,
    Kn7Parser,
    Kn8Kn9Parser,
    Kn10Kn11Parser,
    Kn12Parser,
    Kn13Parser,
    Kn14Parser,
    Kn15Parser,
    Kn16Parser,
    Kn17Parser,
    Kn18Parser,
    Kn19Parser,
    Kn20Parser,
    # abhidhamma
    Abh1Parser,
    Abh2Parser,
    Abh3Parser,
    Abh4Parser,
    Abh5Parser,
    Abh6Parser,
    Abh7Parser,
    # commentary
    VinaParser,
    DnaParser,
    DntParser,
    MnaParser,
    MntParser,
    SnaParser,
    SntParser,
    AnaParser,
    AntParser,
    AbhaParser,
    Kn1aParser,
    Kn2aParser,
    Kn3aParser,
    Kn4aParser,
    Kn5aParser,
    Kn6aParser,
    Kn7aParser,
    Kn8aKn9aParser,
    Kn10aParser,
    Kn12aParser,
    Kn13aParser,
    Kn14aParser,
    Kn15aParser,
    Kn16aParser,
    Kn17aParser,
    Kn19aParser,
    # misc
    KvaParser,
    VismParser,
    ApParser,
    AptParser,
]

BOOK_PARSERS: dict[str, type[BookParser]] = {
    book: cls for cls in PARSER_CLASSES for book in cls.books
}
