name: Deconstructor

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run initial setup script
      run: poetry run bash scripts/bash/initial_setup_run_once.sh

    - name: Build the database
      run: poetry run bash scripts/bash/build_db.sh

    - name: Config settings for all texts
      run: poetry run scripts/db_all_text_setup.py

    - name: Deconstruction Setup
      run: poetry run python db/deconstructor/sandhi_setup.py
        
    - name: Deconstruction Splitter
      run: poetry run python db/deconstructor/sandhi_splitter.py

    - name: Deconstruction Postporocess setup
      run: poetry run python db/deconstructor/sandhi_postprocess.py

    - name: Zip db/deconstructor/output directory
      run: |
        cd db/deconstructor/output
        zip -r ../output.zip .
      working-directory: ./sandhi

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./db/deconstructor/output.zip
        continue-on-error: true
    

