name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:

    # ----------------------------------------
    # Setup (Copied from draft_release.yml)
    # ----------------------------------------

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: 'digitalpalidictionary/dpd-db'
        ref: 'main'
        submodules: 'recursive'
        # Fetch depth 0 to allow committing back to the submodule
        fetch-depth: 0
        # Use PAT to allow pushing to submodule
        token: ${{ secrets.GH_PAT }}

    - name: Remove large dirs
      run: |
        rm -rf ${{ github.workspace }}/resources/bjt/dev/*
        rm -rf ${{ github.workspace }}/resources/sc-data/html_text/*

    - name: Unzip deconstructor_output
      run: |
        cd ${{ github.workspace }}/resources/deconstructor_output
        tar -xzvf deconstructor_output.json.tar.gz
        ls -la
        cd ${{ github.workspace }}/

    - name: Install dictzip
      run: sudo apt-get update && sudo apt-get install -y dictzip

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: uv sync

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'

    # ----------------------------------------
    # Prepare Submodules
    # ----------------------------------------
      
    - name: Sync all submodules with Upstream
      run: |
        for submodule in resources/fdg_dpd resources/bw2 resources/sc-data; do
          echo "Syncing $submodule..."
          cd "$submodule"
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          cd ../..
        done

    # ----------------------------------------
    # Build Database (Copied from draft_release.yml)
    # ----------------------------------------

    - name: Config for GitHub release
      run: uv run python scripts/build/config_github_release.py

    - name: Create dpd.db
      run: touch dpd.db

    - name: Build the database
      run: uv run python scripts/build/db_rebuild_from_tsv.py

    - name: Run initial setup script
      run: uv run bash scripts/bash/initial_setup_run_once.sh

    - name: Create version
      run: uv run python tools/version.py

    - name: Create Inflection Templates
      run: uv run python db/inflections/create_inflection_templates.py

    - name: Create Inflection Tables
      run: uv run python db/inflections/generate_inflection_tables.py

    - name: Update Sanskrit Family Roots
      run: uv run python scripts/build/sanskrit_root_families_updater.py

    - name: Add Root Families
      run: uv run python db/families/family_root.py

    - name: Add Word Families
      run: uv run db/families/family_word.py

    - name: Add Compound Families
      run: uv run python db/families/family_compound.py

    - name: Add Sets
      run: uv run python db/families/family_set.py

    - name: Add Idioms
      run: uv run python db/families/family_idiom.py

    - name: Families to JSON
      run: uv run python scripts/build/families_to_json.py

    - name: Extract Variants
      run: uv run python db/variants/main.py

    - name: Run Deconstructor
      run: uv run python scripts/build/deconstructor_output_add_to_db.py

    - name: Add api ca eva iti to inflections
      run: uv run python scripts/build/api_ca_evi_iti.py

    - name: Transliterate Inflections
      run: uv run python db/inflections/transliterate_inflections.py

    - name: Inflections to Headwords
      run: uv run python db/inflections/inflections_to_headwords.py

    - name: Lookup Variants and Spelling Mistakes
      run: uv run python db/lookup/spelling_mistakes.py

    - name: Lookup Transliterate
      run: uv run python db/lookup/transliterate_lookup_table.py

    - name: Lookup Help and Abbreviations
      run: uv run python db/lookup/help_abbrev_add_to_lookup.py

    - name: Add Frequency
      run: |
        go build -o frequency go_modules/frequency/main.go
        ./frequency

    - name: Run EBT Counter
      run: uv run python scripts/build/ebt_counter.py

    - name: Add EPD to Lookup Table
      run: uv run python db/epd/epd_to_lookup.py

    - name: Test Dealbreakers
      run: uv run python scripts/build/dealbreakers.py

    # ----------------------------------------
    # Run TBW Exporter
    # ----------------------------------------

    - name: Run TBW Exporter
      run: uv run python exporter/tbw/tbw_exporter.py

    # ----------------------------------------
    # Update Submodules
    # ----------------------------------------
    - name: Update All Submodules
      shell: bash
      run: |
        declare -A submodules=(
          ["resources/fdg_dpd"]="fdg https://github.com/o28o/dictPlugin.git"
          ["resources/bw2"]="tbw https://github.com/thebuddhaswords/BW2.git" 
          ["resources/sc-data"]="sc https://github.com/digitalpalidictionary/sc-data.git"
        )

        for path in "${!submodules[@]}"; do
          read name repo <<< "${submodules[$path]}"
          echo "Updating $name submodule..."
          cd "$path"
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status --short
          echo "Recent commits:"
          git log -1 --oneline
          
          git checkout main
          git pull origin main
          
          echo "=== POST-EXPORT STATUS ==="
          git status --short
          git add .
          echo "=== STAGED CHANGES ==="
          git diff --cached --name-only
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "DPD lookup: update $(date +'%d-%b-%y')" || echo "No changes to commit"
          
          echo "=== PRE-PUSH STATUS ==="
          git log -2 --oneline
          git remote -v
          
          echo "=== PUSHING CHANGES ==="
          git push origin main:main
          echo "=== PUSH EXIT CODE: $? ==="
          cd "$GITHUB_WORKSPACE"
        done
